themes.citelibre.code=citelibre
themes.citelibre.name=Theme Citelibre
themes.citelibre.version=2.0.0

themes.citelibre.author=Ville de Paris
themes.citelibre.author_url=https://lutece.paris.fr
themes.citelibre.licence=MIT License

themes.citelibre.css=themes/skin/citelibre/css
themes.citelibre.images=themes/skin/citelibre/images/
themes.citelibre.js=themes/skin/citelibre/js
