DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.banner';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.banner', 'images/banner_v.jpg');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.banner.credits';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.banner.credits', 'Crédit photo : Sophie Robichon / Ville de Paris');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.banner.image.positionx';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.banner.image.positionx', '');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.banner.image.positiony';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.banner.image.positiony', '');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.banner.shown.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.banner.shown.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.banner.showSiteImgEverywhere.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.banner.showSiteImgEverywhere.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.banner.title.bgcolor';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.banner.title.bgcolor', '');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.banner.title.color';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.banner.title.color', '#475390');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.banner.title.padding';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.banner.title.padding', '');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerBrowserWarning.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerBrowserWarning.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerForm.showBannerImg.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerForm.showBannerImg.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerForm.showFormImg.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerForm.showFormImg.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerForm.showFormTitle.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerForm.showFormTitle.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerMessage.CloseButton.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerMessage.CloseButton.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerMessage.Duration';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerMessage.Duration', '0');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerMessage.htmlblock';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerMessage.htmlblock', '');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerMessage.Position';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerMessage.Position', 'top:1rem;right:1rem;');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerMessage.Title';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerMessage.Title', '');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.bannerMessage.Type';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.bannerMessage.Type', 'info');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.config.bannerMessage.CloseButton.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.config.bannerMessage.CloseButton.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.config.datepicker.textblock';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.config.datepicker.textblock', '');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.config.editor.textblock';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.config.editor.textblock', '');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.footer.about';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.footer.about', 'CiteLibre is made for cities, by cities, upon open source principals. <br> <a class="btn btn-link ps-0" href="//:lutece.paris.fr" title="[Nouvelle fenêtre] LUTECE website" target="_blank><img src="images/poweredby.png" alt="Powered by LUTECE"></a> ');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.footer.about.title';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.footer.about.title', 'A propos');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.footer.cookieLabel';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.footer.cookieLabel', 'Cookies management');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.footer.cookieLink';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.footer.cookieLink', '#cookiecitelibrepack');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.footer.links.title';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.footer.links.title', 'Liens importants');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.layout.type.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.layout.type.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.link.showTargetIcon.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.link.showTargetIcon.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.menu.fixedMenu.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.menu.fixedMenu.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.menu.gototop.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.menu.gototop.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.menu.hasDefaultMenu.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.menu.hasDefaultMenu.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.menu.longMenu.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.menu.longMenu.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.menu.sidebarMenu.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.menu.sidebarMenu.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.menu.sidebarMenuCollapse.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.menu.sidebarMenuCollapse.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.menu.siteMapMenu.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.menu.siteMapMenu.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.menu.skipLinkMainId';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.menu.skipLinkMainId', 'main');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.menu.skipLinkMenu.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.menu.skipLinkMenu.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.robotIndex.checkbox';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.robotIndex.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.accessibilityLabel';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.accessibilityLabel', 'Accessibilité : Partiellement conforme');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.accessibilityURL';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.accessibilityURL', 'jsp/site/Portal.jsp?page=htmlpage&amp;htmlpage=1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.cguURL';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.cguURL', 'jsp/site/PopupLegalInfo.jsp');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.cguURLLabel';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.cguURLLabel', 'Condition générales d\'utilisation');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.contactURL';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.contactURL', 'jsp/site/Portal.jsp?page=contact');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.contactURLLabel';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.contactURLLabel', 'Contact');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.cookieURL';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.cookieURL', 'jsp/site/Portal.jsp?page=htmlpage&amp;htmlpage=1');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.cookieURLLabel';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.cookieURLLabel', 'Gestion  des cookies');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.dataURL';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.dataURL', 'jsp/site/PopupCredits.jsp');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.dataURLLabel';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.dataURLLabel', 'Politique de gestion des données à caractère personnel');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.legalURL';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.legalURL', 'jsp/site/PopupLegalInfo.jsp');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.legalURLLabel';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.legalURLLabel', 'Mentions légales');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.Url.search';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.Url.search', 'jsp/site/Portal.jsp?page=search');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.xss.xssChars';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.xss.xssChars', '<>#"&');
DELETE FROM core_datastore WHERE entity_key='themecitelibre.site_property.xss.xssMsg';
INSERT INTO core_datastore VALUES ('themecitelibre.site_property.xss.xssMsg', 'Les caract\\u00e8res &#60; &#62; &#35; et &#34;  &amp; sont interdits dans le contenu de votre message.');
